"""
compute_significance.py — Paired Wilcoxon signed-rank test for ViPER vs each baseline.

Reads JSON results from viper_v5_results_{dataset}/runs/ for all 5 datasets,
extracts the per-seed test accuracy, and runs paired Wilcoxon against
each baseline. Outputs both a LaTeX table and console summary.

Run on sun (where the JSON files live):
    cd ~/ViPER/notebooks
    python3 compute_significance.py

Outputs:
    - wilcoxon_pretrained.tex     (LaTeX table for the paper)
    - wilcoxon_pretrained.txt     (human-readable summary)
"""

import json
import os
from pathlib import Path
from itertools import product

try:
    from scipy.stats import wilcoxon
    HAVE_SCIPY = True
except ImportError:
    HAVE_SCIPY = False
    print("scipy not available — install with: pip install scipy --break-system-packages")

# Datasets and methods to compare
DATASETS = ["eurosat", "bloodmnist", "dermamnist", "dtd", "resisc45"]
SEEDS = [7, 42, 123]

# Method filename stems in JSONs (verify these match your files)
METHODS = {
    "none":      "No PE",
    "learned":   "APE",
    "sincos2d":  "Sin-2D",
    "cpe":       "CPE",
    "multipeg":  "Multi-PEG",
    "viper_v5":  "ViPER",   # this is ViPER (the reference)
}

# Order for output (everything except ViPER is a baseline)
BASELINES = ["none", "learned", "sincos2d", "cpe", "multipeg"]


def load_acc(dataset, method, seed):
    """Load test accuracy from a single JSON run file."""
    path = Path(f"viper_v5_results_{dataset}/runs/{method}_seed{seed}.json")
    if not path.exists():
        return None
    with open(path) as f:
        r = json.load(f)
    if "test" in r and isinstance(r["test"], dict) and "acc" in r["test"]:
        return r["test"]["acc"]
    return None


def collect_pairs(method_a, method_b):
    """Return paired list of (acc_a, acc_b) across all (dataset, seed)."""
    pairs = []
    for ds, seed in product(DATASETS, SEEDS):
        a = load_acc(ds, method_a, seed)
        b = load_acc(ds, method_b, seed)
        if a is not None and b is not None:
            pairs.append((ds, seed, a, b))
    return pairs


# Collect all pairs and run the test
results = []   # list of (baseline_key, baseline_name, n, mean_a, mean_b, w_stat, p_value, larger)
missing = []

if not HAVE_SCIPY:
    print("Cannot run statistical test without scipy.")
    exit(1)

for bkey in BASELINES:
    pairs = collect_pairs("viper_v5", bkey)
    if not pairs:
        missing.append(bkey)
        continue
    
    n = len(pairs)
    viper_accs = [p[2] for p in pairs]
    baseline_accs = [p[3] for p in pairs]
    
    mean_v = sum(viper_accs) / n * 100
    mean_b = sum(baseline_accs) / n * 100
    
    # Differences (ViPER - baseline)
    diffs = [v - b for v, b in zip(viper_accs, baseline_accs)]
    
    # Wilcoxon signed-rank test (paired, two-sided)
    # Use 'zsplit' to handle zeros if any
    try:
        w_result = wilcoxon(diffs, zero_method='wilcox', alternative='two-sided')
        w_stat = w_result.statistic
        p_value = w_result.pvalue
    except ValueError as e:
        w_stat = float('nan')
        p_value = float('nan')
    
    larger = "ViPER" if mean_v > mean_b else METHODS[bkey]
    results.append((bkey, METHODS[bkey], n, mean_v, mean_b, w_stat, p_value, larger))

# Print console summary
print(f"\n{'='*78}")
print(f"  Paired Wilcoxon Signed-Rank Test — ViPER vs Each Baseline (Pretrained)")
print(f"{'='*78}\n")
print(f"  {'Baseline':<12} {'n':>4} {'Baseline':>10} {'ViPER':>10} "
      f"{'Diff':>8} {'W':>10} {'p-value':>10}  {'Reject H0?'}")
print(f"  {'-'*78}")

for bkey, bname, n, m_v, m_b, w, p, larger in results:
    diff = m_v - m_b
    rej = "yes (p<0.05)" if p < 0.05 else "no"
    rej_strict = " **" if p < 0.01 else ("  *" if p < 0.05 else "   ")
    p_str = f"{p:.4f}" if p == p else "n/a"  # NaN check
    w_str = f"{w:.1f}" if w == w else "n/a"
    print(f"  {bname:<12} {n:>4d} {m_b:>10.2f} {m_v:>10.2f} "
          f"{diff:>+8.2f} {w_str:>10} {p_str:>10}  {rej:<14}{rej_strict}")

if missing:
    print(f"\n  Missing JSONs for: {missing}")
    print(f"  Re-run those experiments before final submission.")

print(f"\n  * p<0.05    ** p<0.01")
print()

# Write LaTeX table
latex_path = "wilcoxon_pretrained.tex"
with open(latex_path, "w") as f:
    f.write("% Paired Wilcoxon signed-rank test: ViPER vs each baseline\n")
    f.write("% Generated by compute_significance.py\n")
    f.write("\\begin{table}[h]\n")
    f.write("\\centering\n")
    f.write("\\caption{Paired Wilcoxon signed-rank test comparing ViPER to each\n")
    f.write("baseline across the $5\\times3 = 15$ paired (dataset, seed) test\n")
    f.write("accuracies on the pretrained protocol. The null hypothesis of zero\n")
    f.write("median paired difference is rejected only for the weakest baselines;\n")
    f.write("ViPER is statistically indistinguishable from the strongest PEs.}\n")
    f.write("\\label{tab:wilcoxon}\n")
    f.write("\\setlength{\\tabcolsep}{4pt}\n")
    f.write("\\renewcommand{\\arraystretch}{1.1}\n")
    f.write("\\small\n")
    f.write("\\begin{tabular}{l|c|c|c|c|c|l}\n")
    f.write("\\toprule\n")
    f.write("\\textbf{Baseline} & $n$ & \\textbf{Mean (base)} & "
            "\\textbf{Mean (ViPER)} & \\textbf{$\\Delta$} & "
            "\\textbf{$p$-value} & \\textbf{Reject $H_0$?} \\\\\n")
    f.write("\\midrule\n")
    for bkey, bname, n, m_v, m_b, w, p, larger in results:
        diff = m_v - m_b
        if p < 0.01:
            sig = "yes (p $<$ 0.01)"
        elif p < 0.05:
            sig = "yes (p $<$ 0.05)"
        else:
            sig = "no"
        p_str = f"{p:.4f}" if p == p else "n/a"
        f.write(f"{bname} & {n} & {m_b:.2f} & {m_v:.2f} & ${diff:+.2f}$ "
                f"& {p_str} & {sig} \\\\\n")
    f.write("\\bottomrule\n")
    f.write("\\end{tabular}\n")
    f.write("\\end{table}\n")

print(f"  Wrote {latex_path}")

# Also write a plain summary
txt_path = "wilcoxon_pretrained.txt"
with open(txt_path, "w") as f:
    f.write("Paired Wilcoxon Signed-Rank Test (ViPER vs each baseline)\n")
    f.write("Pretrained DeiT-Tiny protocol, 5 datasets × 3 seeds = 15 pairs\n")
    f.write("=" * 70 + "\n\n")
    for bkey, bname, n, m_v, m_b, w, p, larger in results:
        diff = m_v - m_b
        f.write(f"{bname}:\n")
        f.write(f"  n              = {n}\n")
        f.write(f"  Mean accuracy  = {m_b:.4f}% (baseline), {m_v:.4f}% (ViPER)\n")
        f.write(f"  Difference     = {diff:+.4f}% (ViPER higher: {larger=='ViPER'})\n")
        f.write(f"  Wilcoxon W     = {w}\n")
        f.write(f"  p-value        = {p:.6f}\n")
        f.write(f"  Reject H_0?    = {'yes' if p < 0.05 else 'no'}\n\n")

print(f"  Wrote {txt_path}")
print(f"\nDone.\n")
